<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Auth\Module'                                        => __DIR__ . '/Module.php',
  'Auth\Controller\IndexController'                    => __DIR__ . '/src/Auth/Controller/IndexController.php',
  'Auth\Entity\Login'                                  => __DIR__ . '/src/Auth/Entity/Login.php',
  'Auth\Form\LoginFilter'                              => __DIR__ . '/src/Auth/Form/LoginFilter.php',
  'Auth\Form\LoginForm'                                => __DIR__ . '/src/Auth/Form/LoginForm.php',
  'Auth\Form\LoginFormAwareInterface'                  => __DIR__ . '/src/Auth/Form/LoginFormAwareInterface.php',
  'Auth\Service\AuthCheckerService'                    => __DIR__ . '/src/Auth/Service/AuthCheckerService.php',
  'Auth\Service\AuthCheckerServiceAwareInterface'      => __DIR__ . '/src/Auth/Service/AuthCheckerServiceAwareInterface.php',
  'Auth\Service\AuthCheckerServiceInterface'           => __DIR__ . '/src/Auth/Service/AuthCheckerServiceInterface.php',
  'Auth\Service\AuthServiceAwareInterface'             => __DIR__ . '/src/Auth/Service/AuthServiceAwareInterface.php',
  'Auth\Service\Factory\AuthCheckerFactory'            => __DIR__ . '/src/Auth/Service/Factory/AuthCheckerFactory.php',
  'Auth\Service\Factory\PersistentLoginServiceFactory' => __DIR__ . '/src/Auth/Service/Factory/PersistentLoginServiceFactory.php',
  'Auth\Service\PersistentLoginInterface'              => __DIR__ . '/src/Auth/Service/PersistentLoginInterface.php',
  'Auth\Service\PersistentLoginService'                => __DIR__ . '/src/Auth/Service/PersistentLoginService.php',
  'Auth\Service\PersistentLoginServiceAwareInterface'  => __DIR__ . '/src/Auth/Service/PersistentLoginServiceAwareInterface.php',
);
