language: php

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer --version
  - composer install --no-interaction
  - mkdir data/build
  - mkdir data/docs

script:
  - ./vendor/bin/phpunit -c module/RSS/tests/phpunit.xml --coverage-clover data/build/rss-clover.xml --coverage-html data/docs/rss-coverage
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=*.phtml --ignore=tests/bootstrap.php ./module ./config