<?php
/*
 * This file is part of ZasDev Reader.
 *
 * ZasDev Reader is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ZasDev Reader is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ZasDev Reader. If not, see <http://www.gnu.org/licenses/>.
 */

echo $this->doctype();
?>
<html lang="en">
    <head>
        <?php
        //Title
        echo $this->headTitle($this->translate("ZasDev Reader | Login"));
        //Metas
        echo $this->headMeta()->setCharset("utf-8")
                              ->appendName("description", "")
                              ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                              ->appendName('author', 'Santiago Faci Miguel')
                              ->appendName('author', 'Alejandro Celaya Alastrué')
                              ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        //Styles
        echo $this->headLink();
        // Head Scripts
        echo $this->headScript();
        ?>
    </head>
    <body>
        <div class="login-brand"></div>
        <div id="root">
            <div class="container">
                <?= $this->content ?>
            </div>
            <div id="root_footer"></div>
        </div>
        <footer id="footer">
            <?= $this->render("layout/partials/footer") ?>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>